server:
  port: 8001
spring:
  application:
    name: hystrix-feign
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

feign:
  hystrix:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"